remote_theme: CarolinaPB/CarolinaPB.github.io
url: https://carolinapb.github.io
title: Carolina
redirect_to: https://carolinapb.github.io

navbar-links:
  About Me: https://carolinapb.github.io/aboutme/
  Pipelines:
    - Mapping and variant calling (short reads): https://carolinapb.github.io/WUR_mapping-variant-calling/
    - Population SV calling: https://carolinapb.github.io/population-structural-var-calling-smoove/
    - Population mapping: https://carolinapb.github.io/population-mapping
author: Carolina Pita Barros

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "carolina.pitabarros@wur.nl"
  github: CarolinaPB
  linkedin: "carolina-pita-barros-671077155"
