LONGREADS: Poeciliopsis_gracilis_barcode09.fq.gz
GENOME_SIZE: 6.1e8
SHORTREADS:
  - /lustre/nobackup/WUR/ABGC/moiti001/nanopore-assembly/data/p_gracilis_1.fq.gz
  - /lustre/nobackup/WUR/ABGC/moiti001/nanopore-assembly/data/p_gracilis_2.fq.gz
PREFIX: mother